name: Publish Release

on:
  workflow_dispatch:
    inputs:
      publish:
        description: Publish new package version to npm registry
        required: true
        type: boolean
        default: false

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Common Node and pnpm setup
        uses: ./.github/actions/common-setup

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Config npm registry
        run: pnpm config set registry https://registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm ci:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
