name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SAMBANOVA_API_KEY: ${{ secrets.SAMBANOVA_API_KEY }}

jobs:
  node-tests:
    name: 'Node tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Common Node and pnpm setup
        uses: ./.github/actions/common-setup

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Run Node tests
        run: pnpm test:node

  edge-tests:
    name: 'Edge tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Common Node and pnpm setup
        uses: ./.github/actions/common-setup

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Run Edge tests
        run: pnpm test:edge
