name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SAMBANOVA_API_KEY: ${{ secrets.SAMBANOVA_API_KEY }}

jobs:
  node-tests:
    name: 'Node tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Run Node tests
        run: pnpm test:node

  edge-tests:
    name: 'Edge tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Run Edge tests
        run: pnpm test:edge
